Repository fllesser/nonebot-plugin-parser, pull requests merged in 2025-10, with the labels that each got.

#234 🐞 fix: 修复 B 站长视频解析
  .github/.codecov.yml
  src/nonebot_plugin_resolver2/matchers/render.py
  src/nonebot_plugin_resolver2/parsers/bilibili.py
  tests/parsers/test_bilibili_need_ck.py
Labels: bug, ci

#246 🐞 fix: 修复 tiktok 和 youtube 解析
  pyproject.toml
  src/nonebot_plugin_parser/matchers/__init__.py
  src/nonebot_plugin_parser/parsers/data.py
  src/nonebot_plugin_parser/parsers/tiktok.py
  src/nonebot_plugin_parser/parsers/youtube.py
  src/nonebot_plugin_parser/renders/base.py
  tests/parsers/test_ytdlp.py
Labels: bug

#249 ✨ feat: 优化图片网格布局，改用 flexbox
  src/nonebot_plugin_parser/renders/weibo/templates/weibo.html.jinja
Labels: enhancement

#257 ✨ feat: 优化消息排列
  src/nonebot_plugin_parser/parsers/bilibili.py
  src/nonebot_plugin_parser/parsers/data.py
  src/nonebot_plugin_parser/renders/default.py
  src/nonebot_plugin_parser/renders/weibo.py
  test_url.md
Labels: enhancement

#259 ✨ feat: 添加通用渲染器以支持多平台
  pyproject.toml
  src/nonebot_plugin_parser/config.py
  src/nonebot_plugin_parser/parsers/bilibili/__init__.py
  src/nonebot_plugin_parser/parsers/bilibili/video.py
  src/nonebot_plugin_parser/parsers/data.py
  src/nonebot_plugin_parser/parsers/weibo.py
  src/nonebot_plugin_parser/renders/__init__.py
  src/nonebot_plugin_parser/renders/common.py
  src/nonebot_plugin_parser/renders/default.py
  uv.lock
Labels: enhancement
